version: '2.1'
services:
  dev-nginx:
    restart: always
    image: nginx:latest
    container_name: dev-nginx
    ports:
      - "8080:80"
    volumes:
      - ../workspace:/home/workspace:ro
      - ./nginx/sites/site.conf:/etc/nginx/conf.d/default.conf:ro
